### ISSUE TITLE
Ray tracing solutions are not stable across plattforms

### ISSUE THREAD

**Issue by anelles** [nu-radio/NuRadioMC#166]
When dealing with the built-bot #164 we found that the python ray tracing results are stable to 1e-6 accross plattforms, the C++ results only to 0.05%. This is relative uncertainty on the signal amplitude. 
While not affecting the large picture, this seems worrisome and should be followed up at some point.

**Comment by cg-laser** [comment]
the precision was improved to 1e-9. We also found out that amplitude differences are sometimes due to time differences in the signal propagation time which can have a larger than expected influence because of the binning in time and the limited time resolution of the efield-to-voltage converter. As these small differences are understood and anyway not relevant for any practical purposes, I think we can close this issue.
